### ISSUE TITLE
Issue when using `include` option via rest API

### ISSUE THREAD

**Issue by nicooga** [AgilionApps/ja_serializer#131]
When using the `included` option the serializer throws error:

~~~
Request: GET /api/ttc_interactions?include=phone_numbers&filter[kind]=call
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Keyword.put/3
        (elixir) lib/keyword.ex:453: Keyword.put(%{include: "phone_numbers"}, :include, [phone_numbers: []])
        lib/ja_serializer/builder/top_level.ex:24: JaSerializer.Builder.TopLevel.build/1
        (telmak) web/views/ttc_interaction_view.ex:1: Telmak.TtcInteractionView.format/3
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (telmak) web/controllers/ttc_interaction_controller.ex:1: Telmak.TtcInteractionController.action/2
        (telmak) web/controllers/ttc_interaction_controller.ex:1: Telmak.TtcInteractionController.phoenix_controller_pipeline/2
        (telmak) lib/phoenix/router.ex:261: Telmak.Router.dispatch/2
        (telmak) web/router.ex:1: Telmak.Router.do_call/2
        (telmak) lib/telmak/endpoint.ex:1: Telmak.Endpoint.phoenix_pipeline/1
        (telmak) lib/plug/debugger.ex:93: Telmak.Endpoint."call (overridable 3)"/2
        (telmak) lib/phoenix/endpoint/render_errors.ex:34: Telmak.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
~~~

My source:

~~~elixir
defmodule Telmak.Web do
  # ...
  def jsonapi_controller do
    quote do
      unquote(controller)
      use JaResource
      import Ecto.Query

      def filter(field, query, value) do
        where query, ^Map.to_list(%{String.to_atom(field) => value})
      end
    end
  end
  # ...
  def view do
    quote do
      use Phoenix.View, root: "web/templates"
      alias Telmak.Repo

      # Import convenience functions from controllers
      import Phoenix.Controller, only: [get_csrf_token: 0, get_flash: 2, view_module: 1]

      import Telmak.Router.Helpers
      import Telmak.ErrorHelpers
      import Telmak.Gettext

      use JaSerializer.PhoenixView
      import Telmak.View
    end
  end
  # ...
end

defmodule Telmak.TtcInteractionController do
  use Telmak.Web, :jsonapi_controller
end

defmodule Telmak.UserView do
  use Telmak.Web, :view

  attributes ~w(id email first_name last_name external_avatar_url)a
  preload [:phone_numbers, :geo_points]

  has_many :phone_numbers, serializer: Telmak.PhoneNumberView
  has_many :geo_points, serializer: Telmak.GeoPointView

  def type, do: "users"
end

defmodule Telmak.TtcInteractionView do
  use Telmak.Web, :view

  attributes ~w(kind)a
  preload [:telemarketer, :customer, :phone_number]

  def type, do: "ttc_interactions"

  has_one :customer, serializer: Telmak.UserView, include: true
  has_one :telemarketer, serializer: Telmak.UserView, include: true
  has_one :phone_number, serializer: Telmak.PhoneNumberView, include: true
end
~~~
Not sure whether I should opne the issue here or at JaResource.

**Comment by alanpeabody** [comment]
Yup, this is a JaResource bug, sorry about that.

I have pushed a fix to JaResource master, but note that there were some breaking changes recently.

```elixir
# Before
use JaResource, except: [:delete]

# Now
use JaResource
plug JaResource, except: [:delete]
```

Fix: https://github.com/AgilionApps/ja_resource/commit/1402ec71b915f563d94c04f0d743cb1e0e81b9fa


Also, the filter & sort functions will be getting a changed arity soon and an include function will be introduced for dynamic pre-loading. See: https://github.com/AgilionApps/ja_resource/issues/10 

Let me know if you have any more issues!

**Comment by nicooga** [comment]
Thanks Alan, that seems to have solved the issue. Having implementations
for building standard JSON apis is key (for me?) nowadays, keep it up!
